#!/bin/bash

message=$1

declare -a voices=(Agnes Kathy Princess Vicki Victoria Bruce Fred Junior Ralph Albert "Bad News" Bahh Bells Boing Bubbles Cellos Deranged "Good News" Hysterical "Pipe Organ" Trinoids Whisper Zarvox)


function askVoice {

	id=0

	for v in "${voices[@]}"
	do
	   printf "[$id] $v \t\t"
	   ((id++))

	   if [ $(( $id % 2 )) -eq 0 ]
	   	then echo " " 
	   fi
	done
	echo "  " 
	read -p "What is your singer number ? " choice

	voice=${voices[$choice]}

	echo " - i'm $voice ♫"
	say -v $voice "i'm $voice"

}

askVoice
if [[ -z "$1" ]] 
	then read -p " - What are the lyrics ? " message
fi
read -p " - What is the tempo ( in seconds )? " interval

while true
do
	clear
	
	echo "$voice is saying '$message' every $interval seconds." 
	say \
	-v  $voice \
	$message
	
	for (( i=interval; i>0; i--)); do
    sleep 1 &
    printf "\t next in $i s \r"
    wait    
    printf "\t 							\r"
  done
done

